#!/bin/bash

apt install -y x11-repo clang make openssl openssl-tool wget openssh coreutils gtk2 gtk3
clear

# Official hydra repository
wget -O thc_hydra.tar.gz https://codeload.github.com/vanhauser-thc/thc-hydra/tar.gz/refs/tags/v9.5

# Extract tarball
tar -xvzf thc_hydra.tar.gz
cd thc_hydra

# Configure, compile, and install
./configure --prefix=$PREFIX
make
make install

# Clean up
cd ..
rm -rf thc_hydra thc_hydra.tar.gz
clear
